# Generated by Django 3.1.1 on 2020-11-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_mobileverification_userphonenumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileverification',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mobileverification',
            name='phone_no',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='mobileverification',
            name='verification_code',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
