# Generated by Django 3.1.1 on 2020-11-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201118_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphonenumbers',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
